version: "3"

services:
  aosd:
    image: arisen/arisen:v1.0.6
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  branch: master

    command: /opt/arisen/bin/aosd.sh --max-transaction-time=1000 --data-dir /opt/arisen/bin/data-dir -e
    hostname: aosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"

  awalletd:
    image: arisen/arisen:v1.0.6
    command: /opt/arisen/bin/awalletd --wallet-dir /opt/arisen/bin/data-dir --http-server-address=0.0.0.0:8900
    hostname: awalletd
    ports:
      - 8900:8900
    links:
      - aosd
